---
- name: install and setup dnsmasq
  hosts: localhost
  become: yes
  vars:
    - upstreamdns: 192.168.1.200

  tasks:
    - name: install dnsmasq
      yum:
        name: 
          - dnsmasq
          - bind-utils
        state: latest

    - name: enable dnsmsq.d
      blockinfile:
        path: /etc/dnsmasq.conf
        block: |
          conf-dir=/etc/dnsmasq.d

    - name: create configuration file
      blockinfile:
        path: /etc/dnsmasq.d/custom.conf
        block: |
          resolv-file=/etc/dnsmasq.upstream.conf
          strict-order
          address=/.apps.fcg.ai/192.168.5.86
        create: yes
      notify:
         - restart_dnsmasq

    - name: create upstream record
      blockinfile:
        path: /etc/dnsmasq.upstream.conf
        block: |
          nameserver {{ upstreamdns }}
        create: yes

    - name: start and enable dnsmasq service
      service:
        name: dnsmasq
        state: started
        enabled: yes

    - name: update hosts record
      blockinfile:
        path: /etc/hosts
        block: |
          192.168.5.80 suppiler.fcg.ai suppiler
          192.168.5.81 oc-master-1.fcg.ai oc-master-1
          192.168.5.82 oc-master-2.fcg.ai oc-master-2
          192.168.5.83 oc-node-1.fcg.ai oc-node-1
          192.168.5.84 oc-node-2.fcg.ai oc-node-2
          192.168.5.85 oc-node-3.fcg.ai oc-node-3
          192.168.5.86 oc-master-3.fcg.ai oc-master-3
          192.168.5.11 ceph-mon-1.fcg.ai ceph-mon-1
          192.168.5.12 ceph-node-1.fcg.ai ceph-node-1
          192.168.5.13 ceph-mon-2.fcg.ai ceph-mon-2
          192.168.5.14 ceph-node-2.fcg.ai ceph-node-2
          192.168.5.15 ceph-mon-3.fcg.ai ceph-mon-3
          192.168.5.16 ceph-node-3.fcg.ai ceph-node-3
          192.168.5.80 registry.fcg.ai registry

      notify:
       - restart_dnsmasq

  handlers:
    - name: restart_dnsmasq
      service:
        name: dnsmasq
        state: restarted

