apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-volume     
spec:
  capacity:
    storage: 10Gi    
  accessModes:
    - ReadWriteOnce 
  rbd:              
    monitors:       
      - 192.168.5.11:6789
      - 192.168.5.13:6789
      - 192.168.5.15:6789
    pool: rbd
    image: oc-registry
    user: admin
    secretRef:
      name: ceph-secret 
    fsType: xfs        
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: registry-pvclaim
    namespace: default
