apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: mysqldb
    openshift.io/deployment.name: mysqldb-1
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/scc: restricted
  creationTimestamp: 2018-10-11T16:26:54Z
  generateName: mysqldb-1-
  labels:
    app: mysqldb
    deployment: mysqldb-1
    deploymentconfig: mysqldb
  name: mysqldb-1-p6mfw
  namespace: ceph
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: mysqldb-1
    uid: 71995b09-cd72-11e8-b770-005056a802c7
  resourceVersion: "296719"
  selfLink: /api/v1/namespaces/ceph/pods/mysqldb-1-p6mfw
  uid: 7770e684-cd72-11e8-b770-005056a802c7
spec:
  containers:
  - env:
    - name: MYSQL_DATABASE
      value: quotes
    - name: MYSQL_PASSWORD
      value: redhat
    - name: MYSQL_ROOT_PASSWORD
      value: redhat
    - name: MYSQL_USER
      value: ose
    image: registry.fcg.ai:5000/mysql@sha256:59e5ff6c9d6177d4b98432d055233502451da5c32c3481055b41942785df9e77
    imagePullPolicy: Always
    name: mysqldb
    ports:
    - containerPort: 3306
      protocol: TCP
    - containerPort: 33060
      protocol: TCP
    resources: {}
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000150000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysqldb-volume-1
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-4r8sb
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: default-dockercfg-kr76s
  nodeName: oc-master-3.fcg.ai
  nodeSelector:
    node-role.kubernetes.io/compute: "true"
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000150000
    seLinuxOptions:
      level: s0:c12,c9
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - emptyDir: {}
    name: mysqldb-volume-1
  - name: default-token-4r8sb
    secret:
      defaultMode: 420
      secretName: default-token-4r8sb
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-10-11T08:29:11Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-10-11T08:29:18Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-10-11T16:26:54Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://02004d3a19bd7560b9be830bec34340653a3735a34db5b56359060fa3eb5f043
    image: registry.fcg.ai:5000/mysql@sha256:59e5ff6c9d6177d4b98432d055233502451da5c32c3481055b41942785df9e77
    imageID: docker-pullable://registry.fcg.ai:5000/mysql@sha256:59e5ff6c9d6177d4b98432d055233502451da5c32c3481055b41942785df9e77
    lastState: {}
    name: mysqldb
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-10-11T08:29:18Z
  hostIP: 192.168.5.86
  phase: Running
  podIP: 10.129.0.60
  qosClass: BestEffort
  startTime: 2018-10-11T08:29:11Z
